<?php
if( ! function_exists('shopcozi_default_options') ){
	function shopcozi_default_options(){
        $product_loading_image = get_template_directory_uri() . '/img/prod_loading.gif';

		$data = array(
            'shopcozi_h_logo_width' => 282,
            'shopcozi_h_site_title_fontsize' => 36,
            'shopcozi_h_site_desc_fontsize' => 16,
            'shopcozi_h_transparent_logo' => '',
            
            'shopcozi_nav_account_icon_show' => true,
            'shopcozi_nav_wishlist_icon_show' => true,
            'shopcozi_nav_wishlist_title' => '',
            'shopcozi_nav_compare_icon_show' => true,
            'shopcozi_nav_compare_title' => '',
            'shopcozi_nav_cart_icon_show' => true,
            'shopcozi_nav_btn_label' => '',
            'shopcozi_nav_btn_link' => '',
            'shopcozi_nav_btn_target' => true,           
            'shopcozi_browse_cat_show' => true,           
            'shopcozi_browse_cat_title' => '', 
            'shopcozi_browse_cat_more_title' => '', 
            'shopcozi_browse_cat_nomore_title' => '', 
            'shopcozi_browse_form_show' => true,
            'shopcozi_browse_form_field' => '',     
            'shopcozi_browse_form_dropdown' => '',     
            'shopcozi_h_sticky_show' => true,
            'shopcozi_h_container_width' => 'container', // container-fluid
            'shopcozi_h_style' => 'one',

            'shopcozi_backTotop_show' => true,
            'shopcozi_layout' => 'wide', // boxed
            'shopcozi_accent_color1' => '#D64651',
            'shopcozi_custom_accent_color1_enable' => false,
            'shopcozi_custom_accent_color1' => '#D64651',
            'shopcozi_accent_color2' => '#244bbf',
            'shopcozi_secondary_color' => '#161824',
            'shopcozi_switcher_show' => false,

            'shopcozi_archive_blog_layout' => '0-1-1',
            'shopcozi_archive_blog_leftsidebar' => 'sidebar-2',
            'shopcozi_archive_blog_rightsidebar' => 'sidebar-1',
            'shopcozi_archive_container_width' => 'container',            
            'shopcozi_archive_content_type' => 'excerpt',            
            'shopcozi_archive_excerpt_length' => 30,            
            'shopcozi_archive_readmore_label' => __('Read More','shopcozi'),

            'shopcozi_page_layout' => '0-1-1',
            'shopcozi_page_leftsidebar' => 'sidebar-2',
            'shopcozi_page_rightsidebar' => 'sidebar-1',
            'shopcozi_page_container_width' => 'container',
            
            'shopcozi_woo_layout' => '0-1-1',
            'shopcozi_woo_leftsidebar' => 'sidebar-2',
            'shopcozi_woo_rightsidebar' => 'sidebar-1',
            'shopcozi_woo_container_width' => 'container',
            'shopcozi_woo_show_new_label' => true,
            'shopcozi_woo_show_new_label_time' => 30,
            'shopcozi_woo_new_label_text' => __('New','shopcozi'),
            'shopcozi_woo_show_sale_label_as' => 'percent',
            'shopcozi_woo_sale_label_text' => __('Sale','shopcozi'),
            'shopcozi_woo_feature_label_text' => __('Featured','shopcozi'),
            'shopcozi_woo_out_of_stock_label_text' => __('Sold out','shopcozi'),
            'shopcozi_woo_lazy_load' => true,
            'shopcozi_woo_placeholder_img' => $product_loading_image,
            'shopcozi_woo_effect_product' => true,

            'shopcozi_prod_layout' => '0-1-1',
            'shopcozi_prod_leftsidebar' => 'sidebar-2',
            'shopcozi_prod_rightsidebar' => 'sidebar-1',
            'shopcozi_prod_container_width' => 'container',

            'shopcozi_breadcrumb_show' => true,
            'shopcozi_breadcrumb_title_show' => true,
            'shopcozi_breadcrumb_path_show' => true,
            'shopcozi_breadcrumb_bg_color' => '#f5f5f5',
            'shopcozi_breadcrumb_bg_image' => '',
            'shopcozi_breadcrumb_attachment' => 'scroll',
            'shopcozi_breadcrumb_repeat' => 'no-repeat',
            'shopcozi_breadcrumb_position' => 'center',
            'shopcozi_breadcrumb_size' => 'cover',
            'shopcozi_breadcrumb_overlay' => 'rgba(0,0,0,0.5)',
            'shopcozi_breadcrumb_height' => 670,
            'shopcozi_breadcrumb_style' => 1,

            'shopcozi_footer_middle_columns' => 4,
            'shopcozi_footer_copyright_show' => true,
            'shopcozi_footer_copyright' => '',
            'shopcozi_footer_bg_color' => '',
            'shopcozi_footer_bg_image' => '',
            'shopcozi_footer_bg_attachment' => 'scroll',
            'shopcozi_footer_bg_repeat' => 'no-repeat',
            'shopcozi_footer_bg_position' => 'center',
            'shopcozi_footer_bg_size' => 'cover',
            'shopcozi_footer_overlay' => 'rgba(0,0,0,0.5)',
            'shopcozi_footer_container_width' => 'container',
            
            'shopcozi_p_recent_show' => true,
            'shopcozi_p_recent_title' => '',
            'shopcozi_p_recent_slider_show' => true,
            'shopcozi_p_recent_slider_nav_show' => true,
            'shopcozi_p_recent_slider_nav_position' => 'default', // style1
            'shopcozi_p_recent_slider_dots_show' => true,
            'shopcozi_p_recent_category_filter' => true,
            'shopcozi_p_recent_category' => '',
            'shopcozi_p_recent_posts_per_page' => 10,
            'shopcozi_p_recent_column' => 4,

            'shopcozi_news_show' => true,
            'shopcozi_news_title' => '',
            'shopcozi_news_posts_per_page' => 3,
            'shopcozi_news_category_filter' => true,
            'shopcozi_news_category' => '',
            'shopcozi_news_column' => 3,
            'shopcozi_news_slider_show' => true,
            'shopcozi_news_slider_nav_show' => true,
            'shopcozi_news_slider_nav_position' => 'default', // style1
            'shopcozi_news_slider_dots_show' => true,

            'shopcozi_error_code' => __('4<i class="fa-solid fa-face-smile"></i>4','shopcozi'),
            'shopcozi_error_title' => __('<span>Opps!</span> Page Note Found','shopcozi'),
            'shopcozi_error_desc' => __('We are sorry, but the page you are looking for does not exist.','shopcozi'),
            'shopcozi_error_btn_label' => __('Back To Home','shopcozi'),

            'shopcozi_body_fontsize' => 14,
            'shopcozi_body_lineheight' => 1.7,
            'shopcozi_body_letterspace' => 0.1,
            'shopcozi_body_fontweight' => 400,
            'shopcozi_body_texttransform' => '',
            'shopcozi_h1_fontsize' => 36,
            'shopcozi_h1_lineheight' => 1.2,
            'shopcozi_h1_letterspace' => 0.1,
            'shopcozi_h1_fontweight' => '',
            'shopcozi_h1_texttransform' => '',
            'shopcozi_h2_fontsize' => 32,
            'shopcozi_h2_lineheight' => 1.2,
            'shopcozi_h2_letterspace' => 0.1,
            'shopcozi_h2_fontweight' => '',
            'shopcozi_h2_texttransform' => '',
            'shopcozi_h3_fontsize' => 28,
            'shopcozi_h3_lineheight' => 1.2,
            'shopcozi_h3_letterspace' => 0.1,
            'shopcozi_h3_fontweight' => '',
            'shopcozi_h3_texttransform' => '',
            'shopcozi_h4_fontsize' => 24,
            'shopcozi_h4_lineheight' => 1.2,
            'shopcozi_h4_letterspace' => 0.1,
            'shopcozi_h4_fontweight' => '',
            'shopcozi_h4_texttransform' => '',
            'shopcozi_h5_fontsize' => 20,
            'shopcozi_h5_lineheight' => 1.2,
            'shopcozi_h5_letterspace' => 0.1,
            'shopcozi_h5_fontweight' => '',
            'shopcozi_h5_texttransform' => '',
            'shopcozi_h6_fontsize' => 18,
            'shopcozi_h6_lineheight' => 1.2,
            'shopcozi_h6_letterspace' => 0.1,
            'shopcozi_h6_fontweight' => '',
            'shopcozi_h6_texttransform' => '',
		);

		$data = apply_filters('shopcozi_default_options',$data);
		return $data;
	}
}